# Generated by Django 4.2.5 on 2023-09-15 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Branches', '0001_initial'),
        ('UserProfile', '0002_create_profiles_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Branches.branch'),
        ),
    ]
