#  an_api/auth/
### /auth/login/
POST http://127.0.0.1:8000/an_api/auth/login/
Content-Type: application/json

{
  "email": "pili@mail.com",
  "password": "mientras123"
}


### /auth/logout/
POST http://127.0.0.1:8000/an_api/auth/logout/
Content-Type: application/json
Authorization: Token 5726b9cfaa2ddea19ced469f273e5bd1775d5e8f


### /auth/user/
# Get details about the user
GET http://127.0.0.1:8000/an_api/auth/user/
Authorization: Token 963281d29a2fda4a5a40bfb03731c637a8736e91


# /an_api/registration/
### NOT EXPOSED
POST http://127.0.0.1:8000/an_api/registration/
Content-Type: application/json

{
  "username": "andrew",
  "email": "andrea_del_arco@mail.com",
  "password1": "mientras123",
  "password2": "mientras123",
  "first_name": "Andreita",
  "last_name": "Bonita"
}



### /an_api/registration/user/
# Register a Manager User. Authetication must be of staff or Manager User
POST http://127.0.0.1:8000/an_api/registration/user/
Content-Type: application/json
Authorization: Token 940a2ed30427d829f7ffe05a02f6f096f9fe5da7

{
  "username": "pili",
  "email": "pili@mail.com",
  "password1": "mientras123",
  "password2": "mientras123",
  "first_name": "angelica",
  "last_name": "Alvarez",
  "group": "consumer"
}


### verify-email/
POST http://127.0.0.1:8000/an_api/registration/verify-email/
Content-Type: application/json

{
  "key": "OA:1qggpL:VcCwZB_X35_kPOu5Qs_NxuKrWU-POJIJIO1lTHVdvLw"
}


### users-list
GET http://127.0.0.1:8000/an_api/users-list/
Authorization: Token 53384373dafdb8cc9bfee28b96a5354309190ea1

### user-detail
GET http://127.0.0.1:8000/an_api/users-list/09a0d5a4-dc47-4f12-8755-334273534352/
Authorization: Token 53384373dafdb8cc9bfee28b96a5354309190ea1
