# Generated by Django 4.2.5 on 2023-09-18 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_alter_inventoryregister_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryregister',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InventoryRegister', to='Products.product'),
        ),
    ]
